sched/fair: mark int type and void *ptr as maybe unused
kernel/sched/fair.c:3478:8: error: unused variable 'ptr' [-Werror,-Wunused-variable]
 3478 |         void *ptr = NULL;
      |               ^~~
  CC      kernel/sched/wait.o
kernel/sched/fair.c:11723:6: error: unused variable 'type' [-Werror,-Wunused-variable]
 11723 |         int type = NOHZ_KICK_ANY;
       |             ^~~~

Signed-off-by: meuira <mwardana611@gmail.com>